-- Add migration script here
CREATE TABLE IF NOT EXISTS current_goal (
    id INTEGER PRIMARY KEY AUTOINCREMENT,  
    goal VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
